import Foundation

/// Renders the generated `active.conf` that the managed `include` points at.
///
/// `active.conf` is a small generated file (not a symlink) so the layout stays
/// portable and free of symlink edge cases. Each `include` path is relative to
/// the managed directory, where `active.conf` lives.
enum ActiveConf {
    static func render(profile: String, includes: [String]) -> String {
        var lines = [
            "# Generated by kittymgr. Do not edit; managed by 'kittymgr switch'.",
            "# Active profile: \(profile)",
        ]
        if includes.isEmpty {
            lines.append("# Profile has no .conf files; nothing to include.")
        } else {
            lines.append(contentsOf: includes.map { "include \($0)" })
        }
        return lines.joined(separator: "\n") + "\n"
    }
}
